merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('band/<int:band_id>/', views.band_detail, name='band-detail'),
    path('band/add/', views.band_create, name='band-create'),
    path('listings/', views.listing_list, name='listing-list'), 
    path('listing/<int:listing_id>/', views.listing_detail, name='listing-detail'),
    path('related-listings/<int:band_id>', views.related_listing, name='related-listings'),
    path('about-us/', views.about, name='a-propos'),
    path('contact-us/', views.contact, name='contact'), 
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        ZOUGLOU = 'ZG'
    name = models.CharField(max_length=100)
    biography = models.CharField(max_length=1000)
    genre = models.CharField(choices=Genre.choices, max_length=5)
    year_formed = models.IntegerField(
    validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.BooleanField(default=True)
    official_homepage = models.URLField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = 'RC'
        CLOTHINGS = 'CL'
        POSTERS = 'PT'
        MISCELLANEOUS = 'MS'
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    sold = models.BooleanField(default=False)
    year = models.IntegerField(null=True, blank=True)
    type = models.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        return self.title

merchex/listings/forms.py
from django import forms
from .models import Band

class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)
   
class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ('active', 'official_homepage')

merchex/listings/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.mail import send_mail
from .models import Band, Listing
from .forms import ContactUsForm
from .forms import BandForm

# Create your views here.


def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})


def band_detail(request, band_id):
    band = get_object_or_404(Band, id=band_id)
    return render(request, 'listings/band_detail.html', {'band': band})

def band_create(request):
    if request.method == 'POST':
        bandform = BandForm(request.POST)
        if bandform.is_valid():
            band = bandform.save()
            return redirect('band-detail', band.id)
    else:
        bandform = BandForm()
    return render(request, 'listings/band_create.html', {'bandform': bandform})


def about(request):
    return render(request, 'listings/about.html')


def listing_list(request):
    merchs = Listing.objects.all()
    return render(request, 'listings/listing_list.html', {'merchs': merchs})


def listing_detail(request, listing_id):
    merch = get_object_or_404(Listing, id=listing_id)
    return render(request, 'listings/listing_detail.html', {'merch': merch})


def related_listing(request, band_id):
    band = get_object_or_404(Band, id=band_id)
    return render(request, 'listings/related_listings.html', {'band': band})


def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['melvindogbo@protonmail.com', 'melvindogbo@tutanota.com'],
        )
            return redirect('band-list')
    else:
        form = ContactUsForm()
    return render(request, 'listings/contact.html', {'form': form})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}
{% block title %}About{% endblock  %}

{% block content %}
<h1>À propos</h1> *
<p>Nous adorons merch !</p>
{% endblock  %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}
{% block title %}Create a band{% endblock title %}

{% block content %}
<h1>Create a band</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ bandform.as_p }}
    <input type="submit" value="Creer">
</form>
{% endblock content %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}
{% block title %}Band detail{% endblock title %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
 {% if band.official_homepage %}
 <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
 {% endif %}
</ul>

<p>{{ band.biography }}</p>
<a href="{% url 'related-listings' band.id %}">Listings related to {{band.name}}</a>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends "listings/base.html" %} 
{% block title %}Bands{% endblock  %}

{% block content %}
<h4><a href="{% url 'band-create' %}">Créer un groupe</a></h4>
<ul>
  {% for band in bands %}
  <li><a href="{% url 'band-detail' band.id %}">{{band.name}}</a></li>
  {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>{% block title %}Merch{% endblock %}</title>
  </head>
  <body>
      <nav>
        <a href="{% url 'band-list' %}">Groupes</a>
        <a href="{% url 'listing-list' %}">Annonces</a>
        <a href="{% url 'contact' %}">Contact</a>
        <a href="{% url 'a-propos' %}">A propos</a>
      </nav>
    <div class="container">{% block content %}{% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}
{% block title %}Contact{% endblock  %}

{% block content %}
    <h1>Nous nous soucions de vous</h1>
    <form method="post" action="" novalidate>
        {% csrf_token %} 
        {{form.as_p}}
        <input type="submit" value="Envoyer">
    </form>
{% endblock  %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}
{% block title %}Listing detail{% endblock title %}

{% block content %}

<h2>{{ merch.title }}</h2>
<ul>
    <li>Sold: {{ merch.sold|yesno }}</li>
    <li>Type: {{ merch.get_type_display }}</li>
    <li>Band: {{ merch.band }}</li>
</ul>

<p>{{ merch.description }}</p>
{% endblock content %}

merchex/listings/templates/listings/listing_list.html
{% extends "listings/base.html" %} 
{% block title %}Merchs{% endblock %}

{% block content %}
<ul>
  {% for merch in merchs %}
  <li><a href="{% url 'listing-detail' merch.id %}">{{ merch.title|capfirst }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/related_listings.html
{% extends "listings/base.html" %} 
{% block title %}Related Listings{% endblock %}

{% block content %}
<ul>
  {% for listing in band.listing_set.all %}
  <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title|capfirst }}</a></li>
  {% endfor %}
</ul>
{% endblock %}